name: Generate Resume PDF

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
    types:
      - opened
    paths:
      - "src/pages/resume.js"
      - "src/data/careerData.json"
      - "src/pages/Resume.module.scss"
  # schedule:
  # - cron: "0 0 1 * *" # 00:00 1st of each month

env:
  BOT_NAME: clang-bot
  BOT_EMAIL: clinton.langosch@gmail.com

jobs:
  generate-and-commit-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - run: git checkout HEAD^

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache dependencies
        id: yarn-cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Generate PDF
        run: yarn run pdf:resume

      # - name: Temporarily disable branch protection
      #   id: disable-branch-protection
      #   uses: actions/github-script@v1
      #   with:
      #     github-token: ${{ secrets.CLANG_TOKEN }}
      #     previews: luke-cage-preview
      #     script: |
      #       const result = await github.repos.updateBranchProtection({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         branch: 'main',
      #         required_status_checks: null,
      #         restrictions: null,
      #         enforce_admins: null,
      #         required_pull_request_reviews: null
      #       })
      #       console.log("Result:", result)

      - name: Commit changes
        id: commit-changes
        run: |
          git config --local user.email "${{ env.BOT_EMAIL }}"
          git config --local user.name "${{ env.BOT_NAME }}"
          git add ./src/files/resume-eng.pdf
          git diff-index --quiet HEAD ./src/files/resume-eng.pdf || git commit -m 'chore(resume): regenerate and commit resume PDF'
          echo "::set-output name=commit::true"

      - name: Push Commit
        if: steps.commit-changes.outputs.commit == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.CLANG_TOKEN }}
          branch: ${{ github.head_ref }}

      # - name: Re-enable branch protection
      #   id: enable-branch-protection
      #   if: always()
      #   uses: actions/github-script@v1
      #   with:
      #     github-token: ${{ secrets.CLANG_TOKEN }}
      #     previews: luke-cage-preview
      #     script: |
      #       const result = await github.repos.updateBranchProtection({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         branch: 'main',
      #         required_status_checks: {
      #           strict: false,
      #           contexts: [
      #             'Build the site'
      #           ]
      #         },
      #         restrictions: null,
      #         enforce_admins: true,
      #         required_pull_request_reviews: null
      #       })
      #       console.log("Result:", result)
