name: Test sending to local server

on:
  workflow_dispatch:

env:
  CAREER_DATA_API_URL: ${{ secrets.CAREER_DATA_API_URL }}

jobs:
  fetch-career-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Fetch career data
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"url\": \"${CAREER_DATA_API_URL}\"}" \
          https://c91f-2601-1c2-600-ce80-6529-dc4-b23c-fb89.ngrok-free.app
